### ISSUE TITLE
MethodError with RGB and BGRA

### ISSUE THREAD

**Issue by tbreloff** [JuliaGraphics/ColorVectorSpace.jl#49]
I've been seeing the following with VisualRegressionTests (comparing a reference image to a newly generated PNG), and I'm not sure the proper fix:

```
WARNING: Got error: MethodError(ColorVectorSpace.color_rettype,(ColorTypes.RGB{Float64},ColorTypes.BGRA{Float64}))
```

Before I spend too much time on it, do any fixes spring to mind?  cc @timholy

**Comment by timholy** [comment]
I'm slightly puzzled about that error message. What version of julia are you running? What's the full backtrace?

For reference, it looks like that method [isn't implemented](). The point of the method is to pick a colorant type for the return value for binary operations. It will throw an error if you try to add an `RGB` to a `BGR`, for example, because there isn't a good way to know which one should be chosen. You have an extra issue wrt transparency, too.

**Comment by tbreloff** [comment]
Thanks @timholy.  I presume there is a PNG stored with certain metadata, which is (for some unknown reason) different than the newly generated PNG.  I wonder if there was a change to Images or some related package which changes the way PNGs are loaded?  Either way, don't worry about this until I can produce more useful details... I'll report back.

**Comment by timholy** [comment]
Images doesn't do any Image IO directly; ImageMagick and QuartzImageIO do. But they compute certain type information using code in Images, so really any of the 3 (depending on whether you are on OSX) are possible.

**Comment by timholy** [comment]
Closing due to lack of information.
